/**
 * exporter.js — Download and clipboard export utilities
 */

/* ── Individual File Download ── */
function downloadFile(filename, content) {
  const blob = new Blob([content], { type: 'text/markdown;charset=utf-8' });
  const url  = URL.createObjectURL(blob);
  const a    = document.createElement('a');
  a.href     = url;
  a.download = filename;
  document.body.appendChild(a);
  a.click();
  document.body.removeChild(a);
  URL.revokeObjectURL(url);
  showToast(`Downloaded ${filename}`, 'success');
}

/* ── ZIP Bundle Download ── */
async function downloadAllAsZip(docs, projectName = 'documentation') {
  if (typeof JSZip === 'undefined') {
    showToast('JSZip not loaded. Please refresh.', 'error');
    return;
  }

  const zip = new JSZip();
  const docFolder = zip.folder('docs');

  const files = [
    { name: 'README.md',       content: docs.readme       },
    { name: 'INSTALLATION.md', content: docs.installation },
    { name: 'API_DOCS.md',     content: docs.api          },
    { name: 'ARCHITECTURE.md', content: docs.architecture },
    { name: 'CONTRIBUTING.md', content: docs.contributing },
    { name: 'CHANGELOG.md',    content: docs.changelog    },
  ];

  for (const f of files) {
    if (f.content) docFolder.file(f.name, f.content);
  }

  // Add an index file
  const index = `# Documentation Package

Generated by AI Doc Generator on ${new Date().toLocaleDateString()}

## Files Included

| File | Description |
|------|-------------|
| README.md | Project overview, installation, and usage |
| INSTALLATION.md | Detailed setup guide |
| API_DOCS.md | API endpoint reference |
| ARCHITECTURE.md | Architecture and design guide |
| CONTRIBUTING.md | Contribution guidelines |
| CHANGELOG.md | Version history |
`;
  docFolder.file('INDEX.md', index);

  try {
    const blob = await zip.generateAsync({ type: 'blob', compression: 'DEFLATE' });
    const url  = URL.createObjectURL(blob);
    const a    = document.createElement('a');
    a.href     = url;
    a.download = `${projectName}-docs.zip`;
    document.body.appendChild(a);
    a.click();
    document.body.removeChild(a);
    URL.revokeObjectURL(url);
    showToast('All documentation downloaded as ZIP!', 'success');
  } catch (err) {
    showToast('Failed to create ZIP. Try downloading individually.', 'error');
    console.error(err);
  }
}

/* ── Clipboard Copy ── */
async function copyToClipboard(content) {
  try {
    await navigator.clipboard.writeText(content);
    showToast('Copied to clipboard!', 'success');
  } catch {
    // Fallback
    const ta = document.createElement('textarea');
    ta.value = content;
    ta.style.position = 'fixed';
    ta.style.opacity = '0';
    document.body.appendChild(ta);
    ta.focus();
    ta.select();
    try {
      document.execCommand('copy');
      showToast('Copied to clipboard!', 'success');
    } catch {
      showToast('Copy failed. Please select and copy manually.', 'error');
    }
    document.body.removeChild(ta);
  }
}

/* ── Toast Notification ── */
let toastTimeout = null;

function showToast(message, type = 'info') {
  const toast = document.getElementById('toast');
  if (!toast) return;

  const icons = { success: '✅', error: '❌', info: 'ℹ️', warning: '⚠️' };
  toast.innerHTML = `<span>${icons[type] || icons.info}</span><span>${message}</span>`;
  toast.className = `toast ${type}`;
  toast.classList.remove('hidden');

  // Warnings linger a little longer so users can read them
  const duration = type === 'warning' ? 5000 : 3500;
  if (toastTimeout) clearTimeout(toastTimeout);
  toastTimeout = setTimeout(() => {
    toast.classList.add('hidden');
  }, duration);
}

