sonar.projectKey=abdullahaz-create_AI-based-doc-generator
sonar.organization=abdullahaz-create

sonar.sources=js,src
sonar.tests=tests

sonar.javascript.lcov.reportPaths=coverage/lcov.info

sonar.sourceEncoding=UTF-8